// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuBookOpen, LuChevronRight, LuContact, LuGithub, LuGlobe, LuImage, LuLinkedin, LuMail, LuPhone, LuSettings, LuStar, LuTwitter } from 'react-icons/lu';
import { FaArrowsUpDownLeftRight, FaBullseye, FaClockRotateLeft, FaCompass, FaEnvelope, FaEye, FaFacebook, FaFeather, FaFileLines, FaHeadset, FaInstagram, FaLayerGroup, FaLifeRing, FaLink, FaLinkedin, FaMapPin, FaPalette, FaPhone, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaUniversalAccess, FaWandMagicSparkles, FaXmark, FaYoutube } from 'react-icons/fa6';
import { SiFacebook } from 'react-icons/si';

export const iconMap = {
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bullseye': FaBullseye,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:envelope': FaEnvelope,
  'fa6:eye': FaEye,
  'fa6:facebook': FaFacebook,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:instagram': FaInstagram,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:linkedin': FaLinkedin,
  'fa6:map-pin': FaMapPin,
  'fa6:palette': FaPalette,
  'fa6:phone': FaPhone,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'fa6:youtube': FaYoutube,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'lu:star': LuStar,
  'lu:twitter': LuTwitter,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
