// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuBookOpen, LuChartBar, LuChevronRight, LuCode, LuContact, LuGithub, LuGlobe, LuImage, LuLinkedin, LuMail, LuMegaphone, LuMinus, LuMousePointer, LuPhone, LuPlus, LuSearch, LuSettings, LuThumbsUp, LuTwitter } from 'react-icons/lu';
import { FaBullhorn, FaCode } from 'react-icons/fa';
import { SiFacebook } from 'react-icons/si';
import { FaArrowsUpDownLeftRight, FaBullseye, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaLayerGroup, FaLifeRing, FaLink, FaPalette, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';

export const iconMap = {
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bullseye': FaBullseye,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:palette': FaPalette,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'fa:bullhorn': FaBullhorn,
  'fa:code': FaCode,
  'lu:arrow-right': LuArrowRight,
  'lu:book-open': LuBookOpen,
  'lu:chart-bar': LuChartBar,
  'lu:chevron-right': LuChevronRight,
  'lu:code': LuCode,
  'lu:contact': LuContact,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:megaphone': LuMegaphone,
  'lu:minus': LuMinus,
  'lu:mouse-pointer': LuMousePointer,
  'lu:phone': LuPhone,
  'lu:plus': LuPlus,
  'lu:search': LuSearch,
  'lu:settings': LuSettings,
  'lu:thumbs-up': LuThumbsUp,
  'lu:twitter': LuTwitter,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
